### ISSUE TITLE
파일 정리

### ISSUE THREAD

**Issue by okms00909** [KMU-OSS-Laboratory/Open-Source-in-the-Enteprise#5]
현재 루트 디렉토리에 책 내용 파일과 README 파일이 뒤섞여 있고, 파일들이 챕터순이 아닌 알파벳 순으로 정렬되어 있는 데다가 원 제목 그대로가 아닌 요약되어 있어서 상당히 찾아보기가 불편한 상태입니다.

```text
src/
  ch00-00-acknowledgments.md
  ...
  ch04-00-open-source-in-the-enterprise.md
  ...
  ch07-00-adopting-and-using-open-source-code.md
  ch07-01-create-and-document-an-internal-open-source-policy.md
  ch07-02-formalize-your-strategy-through-an-ospo.md
  ...
  역자-서문.md
  역자-소개.md
README.md
```

위 같은 식으로 src/ 디렉토리등을 만들어 파일을 정리하고, 원 제목을 사용하고 챕터를 파일명 앞에 붙여서 바로 알 수 있도록 하는 것이 어떨까 싶습니다. (챕터 번호는 현재 README 파일의 목차 순서대로 붙였으며, 역자 서문, 소개 등의 원문에 존재하지 않는 경우는 챕터를 따로 적용하지 않았습니다)

**Comment by minsuklee** [comment]
좋은 생각입니다. ㅈ

**Comment by minsuklee** [comment]
반영 완료.. 각 subsection를 더 작은 파일로 나누는 것은 아직 보류 했습니다.
각자 작업하고도 merge가 잘 될 것 같아서요..

**Comment by okms00909** [comment]
빠른 반영 감사드립니다!
